application: atelier-sou
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: front/dist/index.html
  upload: front/dist/index.html

- url: /
  static_dir: front/dist

skip_files:
- front/dev/.*
